In [1]:
import pandas

In [2]:
import numpy

In [3]:
db = pandas.read_csv("marks.csv")

In [4]:
db

Name  Hours  Marks
0  Ashutosh      5     50
1  Shwetabh      4     40
2  Shivangi      6     60
3    Shweta      7     70
4   Varshaa      8     80

In [5]:
X, y = db["Hours"], db["Marks"]

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
mind = LinearRegression()

In [8]:
X

0    5
1    4
2    6
3    7
4    8
Name: Hours, dtype: int64

In [9]:
X = X.values

In [10]:
X

array([5, 4, 6, 7, 8], dtype=int64)

In [11]:
X.shape

(5,)

In [12]:
X = X.reshape([5,1])

In [13]:
mind.fit(X,y.values.reshape([5,1]))

LinearRegression()

In [14]:
mind.coef_

array([[10.]])

In [15]:
mind.intercept_

array([1.42108547e-14])

In [16]:
mind.predict([[10]])

array([[100.]])

In [17]:
import joblib

In [18]:
joblib.dump(mind, "model.pkl")

['model.pkl']